Repository MurmurationsNetwork/MurmurationsServices, pull requests merged in 2023-06, with the labels that each got.

#508 continuing the refactoring of the validation service
  pkg/backoff/backoff.go
  pkg/elastic/client_interface.go
  pkg/mongo/client.go
  pkg/nats/client_interface.go
  pkg/retry/retry.go
  pkg/retry/retry_test.go
  services/validation/internal/controller/rest/ping_handler.go
  services/validation/internal/controller/rest/ping_handler_test.go
  services/validation/internal/service/validation_service.go
  services/validation/internal/service/validation_service_test.go
Labels: design & code

#510 refactor the validatenode package
  docs/dot-github-directory.md
  pkg/core/README.md
  pkg/validatenode/validatenode.go
  services/dataproxy/internal/usecase/batch_usecase.go
  services/index/internal/adapter/controller/rest/node_handler.go
  services/validation/README.md
  services/validation/internal/service/validation_service.go
Labels: design & code

#512 fix: handle missing GitHub token, log when no new commits
  pkg/httputil/httputil.go
  services/cronjob/schemaparser/pkg/schemaparser/cronjob.go
Labels: bug

#518 refactor: ignore redirected `profile_url`s
  pkg/httputil/httputil.go
  services/index/internal/adapter/controller/rest/node_dto.go
  services/index/internal/usecase/node_usecase.go
Labels: enhancement

#520 feat: Improve SchemaParser Loading Speed
  services/cronjob/schemaparser/internal/service/schema_service.go
Labels: improvement

#523 feat: add `name` field to index
  build/index/docker/Dockerfile-prod
  docs/db-es-updating/issue-517.md
  services/index/cmd/esseeder/main.go
  services/index/global/init.go
  services/index/internal/adapter/controller/rest/node_handler.go
  services/index/internal/entity/query/query_dao.go
  services/index/internal/entity/query/query_entity.go
Labels: enhancement

#525 chore: remove update ES "name" field script and docs
  build/index/docker/Dockerfile-prod
  docs/db-es-updating/issue-517.md
  services/index/cmd/esseeder/main.go
Labels: enhancement

#522 refactor the index service - part 1
  api/README.md
  api/rest/v2/index.yaml
  api/rest/v2/library.yaml
  services/README.md
  services/index/README.md
  services/index/config/config.go
  services/index/global/init.go
  services/index/internal/adapter/controller/event/constant.go
  services/index/internal/adapter/repository/db/error.go
  services/index/internal/adapter/repository/db/node_dao.go
  services/index/internal/adapter/repository/db/node_mock.go
  services/index/internal/controller/event/listeners.go
  services/index/internal/controller/rest/export_test.go
  services/index/internal/controller/rest/node_handler.go
  services/index/internal/controller/rest/request.go
  services/index/internal/controller/rest/request_test.go
  services/index/internal/controller/rest/respond.go
  services/index/internal/entity/node.go
  services/index/internal/index/consts.go
  services/index/internal/index/errors.go
  services/index/internal/index/errors_test.go
  services/index/internal/model/node.go
  services/index/internal/model/query/query_dao.go
  services/index/internal/model/query/query_entity.go
  services/index/internal/repository/db/db.go
  services/index/internal/service/node.go
  services/index/internal/service/node_test.go
  services/index/internal/usecase/node_usecase.go
  services/index/internal/usecase/node_usecase_test.go
  services/index/pkg/index/envvar.go
  services/index/pkg/index/service.go
Labels: design & code

#528 feat: add name parameter to the /get-nodes route
  services/index/internal/controller/rest/node_handler.go
Labels: enhancement
