Repository MurmurationsNetwork/MurmurationsServices, pull requests merged in 2023-07, with the labels that each got.

#531 refactor: fix deprecated elastic type and mongo mergeOptions
  .golangci.yml
  pkg/elastic/client.go
  pkg/elastic/constant.go
  pkg/mongo/client.go
Labels: enhancement

#532 refactor: add error message in dataproxyupdater
  services/cronjob/dataproxyupdater/cmd/dataproxyupdater/main.go
Labels: improvement

#536 refactor: clean up SetNodeValid logic
  pkg/countries/countries.go
  pkg/validateurl/validateurl.go
  services/index/internal/model/export_test.go
  services/index/internal/model/node.go
  services/index/internal/model/node_test.go
  services/index/internal/model/nodes.go
  services/index/internal/model/profile.go
  services/index/internal/model/profile_test.go
  services/index/internal/service/node.go
  services/index/internal/service/node_test.go
Labels: design & code

#543 refactor: improve the ES query logic
  pkg/elastic/query_builder.go
  services/index/internal/repository/es/queries.go
Labels: design & code

#544 refactor: improve schema validation logic
  pkg/schemavalidator/builder.go
  pkg/schemavalidator/schemavalidator.go
  pkg/schemavalidator/validationresult.go
  services/dataproxy/internal/service/batch.go
  services/index/internal/controller/rest/node_handler.go
  services/validation/internal/service/validation.go
  services/validation/internal/service/validation_test.go
Labels: design & code
