Repository MurmurationsNetwork/MurmurationsServices, pull requests merged in 2023-05, with the labels that each got.

#454 Check profile_hash before changing last_updated
  common/httputil/httputil.go
  services/index/internal/usecase/node_usecase.go
  services/validation/internal/service/validation_service.go
Labels: improvement

#457 Add countries/map.json file to library and create an endpoint
  charts/murmurations/charts/library/templates/library/config.yaml
  common/countries/countries.go
  common/countries/countries_test.go
  services/index/internal/adapter/repository/db/db.go
  services/library/config/config.go
  services/library/docker/Dockerfile-prod
  services/library/internal/app/url_mappings.go
  services/library/internal/controller/http/country_handler.go
  services/library/static/countries.json
  tests/e2e-tests.json
Labels: improvement

#460 Update schema-parser to retrieve data from GitHub API directly
  .doc/secrets.md
  charts/murmurations/charts/schemaparser/templates/schemaparser/config.yaml
  common/httputil/httputil.go
  services/cronjob/schemaparser/cmd/schemaparser/main.go
  services/cronjob/schemaparser/config/config.go
  services/cronjob/schemaparser/internal/domain/schema.go
  services/cronjob/schemaparser/internal/service/schema_service.go
  services/cronjob/schemaparser/internal/service/schema_service_test.go
  tests/e2e-tests.json
Labels: improvement

#461 Fix TestFindAlpha2ByName test
  common/countries/countries_test.go
Labels: bug

#464 Fix properties order in Library service
  common/countries/countries_test.go
  go.mod
  go.sum
  services/cronjob/schemaparser/internal/domain/schema.go
  services/cronjob/schemaparser/internal/service/schema_service.go
  services/library/internal/repository/db/schema.go
Labels: bug

#465 Add index removal time to deleted status response
  charts/murmurations/charts/index/templates/index/config.yaml
  charts/murmurations/charts/nodecleaner/templates/nodecleaner/config.yaml
  common/dateutil/dateutil.go
  common/dateutil/dateutil_test.go
  services/cronjob/nodecleaner/cmd/nodecleaner/main.go
  services/cronjob/nodecleaner/config/config.go
  services/cronjob/nodecleaner/internal/service/node_service.go
  services/index/config/config.go
  services/index/internal/adapter/controller/http/node_handler.go
Labels: improvement

#476 Update the Time-to-Live (TTL) values in the nodecleaner service to make them readable
  charts/murmurations/charts/nodecleaner/templates/nodecleaner/config.yaml
  services/cronjob/nodecleaner/config/config.go
  services/cronjob/nodecleaner/internal/service/node_service.go
Labels: improvement

#484 doc: add Running E2E Tests Locally section
  .doc/secrets.md
  Makefile
  README.md
Labels: documentation

#493 Make e2e tests run with pre-commit
  .pre-commit-config.yaml
  docs/add-git-hook.md
  tests/e2e-tests.json
Labels: testing

#494 Remove CDN urls
  charts/murmurations/charts/dataproxy/templates/dataproxy/config.yaml
  charts/murmurations/charts/index/templates/index/config.yaml
  charts/murmurations/charts/validation/templates/validation/config.yaml
  services/dataproxy/config/config.go
  services/index/config/config.go
  services/validation/config/config.go
  services/validation/pkg/validation/service.go
Labels: bug

#496 Add git hook manually and merge it with pre-commit package
  .pre-commit-config.yaml
  README.md
Labels: improvement
