Repository MurmurationsNetwork/MurmurationsServices, pull requests merged in 2024-03, with the labels that each got.

#697 Make Library fetch schemas locally from local dev
  .gitignore
  charts/murmurations/charts/schemaparser/templates/schemaparser/config.yaml
  docs/testing-schemas-in-local.md
  library/fields/.gitkeep
  library/schemas/.gitkeep
  services/schemaparser/config/config.go
  services/schemaparser/internal/schemaparser/parser.go
  services/schemaparser/internal/service/schema.go
  services/schemaparser/pkg/schemaparser/cronjob.go
Labels: enhancement

#712 doc: add set up kibana error filters section to debugging guide
  docs/debugging-guide/README.md
  docs/debugging-guide/assets/images/kibana-add-filter.png
  docs/debugging-guide/assets/images/kibana-save-search.png
  docs/debugging-guide/assets/images/kibana-view-saved-search.png
Labels: documentation

#720 Fix doc
  docs/other-platforms/04-goatcounter.md
  docs/rancher/09-setup-logging/README.md
  scripts/ubuntu_setup.sh
Labels: documentation

#721 Add maintenance mode
  .github/workflows/main.yaml
  .github/workflows/pr.yaml
  .github/workflows/redeploy.yml
  .github/workflows/test.yaml
  Makefile
  build/maintenance/docker/Dockerfile
  build/maintenance/docker/default.conf
  build/maintenance/docker/message.json
  build/maintenance/mk/Makefile
  charts/murmurations/charts/maintenance/.helmignore
  charts/murmurations/charts/maintenance/Chart.yaml
  charts/murmurations/charts/maintenance/templates/dpl.yaml
  charts/murmurations/charts/maintenance/templates/svc.yaml
  charts/murmurations/charts/maintenance/values.yaml
  docs/maintenance.md
Labels: enhancement

#726 Check it again and eliminate the errors if there is an API glitch
  services/dataproxyupdater/internal/model/update.go
  services/dataproxyupdater/internal/repository/mongo/update.go
  services/dataproxyupdater/internal/service/update.go
  services/dataproxyupdater/pkg/dataproxyupdater/service.go
Labels: improvement
